name: wallet_example
description: Demonstrates how to use the wallet plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^2.1.0
  tiki_wallet:
    path: ../
  cupertino_icons: ^1.0.2
  uuid: ^3.0.5
  tiki_localchain: ^0.0.5
  pointycastle: ^3.5.2
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.0

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

flutter:
  uses-material-design: true
